import * as fs from "fs";
import * as path from "path";
import { reloadCaddyConfig } from "../../system/CaddyAdminService";

function matcherNameFor(routeId: string): string {
  const sanitized = routeId.replace(/[^a-zA-Z0-9_]/g, "_");
  return `vivd_studio_${sanitized}`;
}

export class DockerRuntimeRouteService {
  private readonly options: {
    getRoutesDir: () => string;
    getRoutePath: (routeId: string) => string;
  };

  constructor(options: {
    getRoutesDir: () => string;
    getRoutePath: (routeId: string) => string;
  }) {
    this.options = options;
  }

  getRoutePath(routeId: string): string {
    return this.options.getRoutePath(routeId);
  }

  private routeFilePath(routeId: string): string {
    return path.join(this.options.getRoutesDir(), `studio-${routeId}.caddy`);
  }

  async upsertRuntimeRoute(options: {
    routeId: string;
    containerName: string;
    targetPort: number;
  }): Promise<string> {
    const routesDir = this.options.getRoutesDir();
    fs.mkdirSync(routesDir, { recursive: true });

    const routePath = this.getRoutePath(options.routeId);
    const matcher = matcherNameFor(options.routeId);
    const content = `# Auto-generated by Vivd for studio runtime ${options.routeId}
@${matcher} path ${routePath} ${routePath}/*
handle @${matcher} {
    uri strip_prefix ${routePath}
    reverse_proxy ${options.containerName}:${options.targetPort} {
        header_up X-Forwarded-Prefix ${routePath}
    }
}
`;

    const filePath = this.routeFilePath(options.routeId);
    const existing = fs.existsSync(filePath)
      ? fs.readFileSync(filePath, "utf-8")
      : null;
    if (existing === content) {
      return routePath;
    }

    fs.writeFileSync(filePath, content, "utf-8");
    await reloadCaddyConfig();
    return routePath;
  }

  async removeRuntimeRoute(routeId: string): Promise<void> {
    const filePath = this.routeFilePath(routeId);
    if (!fs.existsSync(filePath)) return;
    fs.unlinkSync(filePath);
    await reloadCaddyConfig();
  }
}
