services:
  backend:
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - ./backend/generated:/app/generated
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - node_modules/
            - generated/
        - action: rebuild
          path: ./backend/package.json

  frontend:
    env_file:
      - .env
    command: npm run dev -- --host
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
