services:
  backend:
    build:
      context: ./backend
      target: prod
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - PORT=3000
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      - backend_data:/app/generated
    depends_on:
      - postgres
    networks:
      - landing-page-agent-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: prod
    depends_on:
      - backend
    networks:
      - landing-page-agent-network

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - landing-page-agent-network

networks:
  landing-page-agent-network:


volumes:
  postgres_data:
  backend_data:
