// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiHasUsersData, GetApiHasUsersResponses, GetApiStatusBySlugData, GetApiStatusBySlugResponses, PostApiGenerateData, PostApiGenerateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Trigger generation
 */
export const postApiGenerate = <ThrowOnError extends boolean = false>(options: Options<PostApiGenerateData, ThrowOnError>) => (options.client ?? client).post<PostApiGenerateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/generate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Check if users exist
 */
export const getApiHasUsers = <ThrowOnError extends boolean = false>(options?: Options<GetApiHasUsersData, ThrowOnError>) => (options?.client ?? client).get<GetApiHasUsersResponses, unknown, ThrowOnError>({ url: '/api/has-users', ...options });

/**
 * Get generation status
 */
export const getApiStatusBySlug = <ThrowOnError extends boolean = false>(options: Options<GetApiStatusBySlugData, ThrowOnError>) => (options.client ?? client).get<GetApiStatusBySlugResponses, unknown, ThrowOnError>({ url: '/api/status/{slug}', ...options });
