// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type PostApiGenerateData = {
    body: {
        url: string;
    };
    path?: never;
    query?: never;
    url: '/api/generate';
};

export type PostApiGenerateResponses = {
    /**
     * Generation started
     */
    200: {
        status?: string;
        slug?: string;
        message?: string;
    };
};

export type PostApiGenerateResponse = PostApiGenerateResponses[keyof PostApiGenerateResponses];

export type GetApiHasUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/has-users';
};

export type GetApiHasUsersResponses = {
    /**
     * User count status
     */
    200: {
        hasUsers?: boolean;
    };
};

export type GetApiHasUsersResponse = GetApiHasUsersResponses[keyof GetApiHasUsersResponses];

export type GetApiStatusBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/status/{slug}';
};

export type GetApiStatusBySlugResponses = {
    /**
     * Status
     */
    200: {
        status?: string;
        url?: string;
    };
};

export type GetApiStatusBySlugResponse = GetApiStatusBySlugResponses[keyof GetApiStatusBySlugResponses];
