// AUTO-GENERATED by packages/installed-plugins/scripts/generate-surface-registries.mjs. Do not edit manually.
import { definePluginPackageDescriptors } from "@vivd/plugin-sdk";
import type { PluginPackageDescriptor } from "@vivd/plugin-sdk";
import installedPlugin0 from "@vivd/plugin-contact-form/cli/plugin";
import installedPlugin1 from "@vivd/plugin-analytics/cli/plugin";
import installedPlugin2 from "@vivd/plugin-newsletter/cli/plugin";

type CliPluginPackage = PluginPackageDescriptor<string, unknown>;

export const installedCliPluginDescriptors = definePluginPackageDescriptors([
  installedPlugin0,
  installedPlugin1,
  installedPlugin2,
] as const satisfies readonly CliPluginPackage[]);
