// AUTO-GENERATED by packages/installed-plugins/scripts/generate-surface-registries.mjs. Do not edit manually.
import {
  buildSharedProjectPluginUiRegistry,
  definePluginPackageDescriptors,
} from "@vivd/plugin-sdk";
import type { ComponentType } from "react";
import type {
  PluginPackageDescriptor,
  SharedProjectPluginUiDefinition,
} from "@vivd/plugin-sdk";
import installedPlugin0 from "@vivd/plugin-contact-form/frontend/plugin";
import installedPlugin1 from "@vivd/plugin-analytics/frontend/plugin";
import installedPlugin2 from "@vivd/plugin-newsletter/frontend/plugin";
import installedPlugin3 from "@vivd/plugin-table-booking/frontend/plugin";

interface InstalledFrontendPluginModule {
  pluginId: string;
  projectUi?: SharedProjectPluginUiDefinition & {
    ProjectPage?: ComponentType<{
      projectSlug: string;
      isEmbedded?: boolean;
    }>;
  };
}

type FrontendPluginPackage = PluginPackageDescriptor<
  string,
  InstalledFrontendPluginModule
>;

export const installedFrontendPluginDescriptors =
  definePluginPackageDescriptors([
  installedPlugin0,
  installedPlugin1,
  installedPlugin2,
  installedPlugin3,
  ] as const satisfies readonly FrontendPluginPackage[]);

export const installedFrontendSharedProjectPluginUiRegistry =
  buildSharedProjectPluginUiRegistry(installedFrontendPluginDescriptors);

export const installedFrontendPluginModules =
  installedFrontendPluginDescriptors.flatMap((descriptor) =>
    descriptor.frontend ? [descriptor.frontend] : [],
  );
