// AUTO-GENERATED by plugins/installed/scripts/generate-surface-registries.mjs. Do not edit manually.
import { definePluginPackageDescriptors } from "@vivd/plugin-sdk";
import type { PluginPackageDescriptor } from "@vivd/plugin-sdk";
import installedPlugin1 from "@vivd/plugin-contact-form/cli/plugin";
import installedPlugin2 from "@vivd/plugin-analytics/cli/plugin";
import installedPlugin3 from "@vivd/plugin-newsletter/cli/plugin";
import installedPlugin4 from "@vivd/plugin-table-booking/cli/plugin";

type CliPluginPackage = PluginPackageDescriptor<string, unknown>;

export const installedCliPluginDescriptors = definePluginPackageDescriptors([
  installedPlugin1,
  installedPlugin2,
  installedPlugin3,
  installedPlugin4,
] as const satisfies readonly CliPluginPackage[]);
