// AUTO-GENERATED by plugins/installed/scripts/generate-surface-registries.mjs. Do not edit manually.
import {
  definePluginBundleEntries,
  definePluginPackageDescriptors,
  extractPluginIds,
} from "@vivd/plugin-sdk";
import installedPlugin0 from "@vivd/plugin-contact-form/descriptor";
import installedPlugin1 from "@vivd/plugin-analytics/descriptor";
import installedPlugin2 from "@vivd/plugin-newsletter/descriptor";
import installedPlugin3 from "@vivd/plugin-table-booking/descriptor";

export const installedPluginDescriptors =
  definePluginBundleEntries([
  installedPlugin0,
  installedPlugin1,
  installedPlugin2,
  installedPlugin3,
  ] as const);

export const installedPluginManifests = definePluginPackageDescriptors(
  installedPluginDescriptors.map((descriptor) => descriptor.manifest) as readonly (
    typeof installedPluginDescriptors
  )[number]["manifest"][],
);

export const INSTALLED_PLUGIN_IDS = extractPluginIds(installedPluginManifests);
export type InstalledPluginId = (typeof INSTALLED_PLUGIN_IDS)[number];
export type InstalledPluginDescriptor =
  (typeof installedPluginDescriptors)[number];

export function listInstalledPluginAgentHints(
  enabledPluginIds?: readonly string[],
): string[] {
  const enabled = new Set(
    (enabledPluginIds ?? []).map((pluginId) => pluginId.trim()).filter(Boolean),
  );
  if (enabled.size === 0) return [];

  const seen = new Set<string>();
  const hints: string[] = [];

  for (const descriptor of installedPluginDescriptors) {
    if (!enabled.has(descriptor.pluginId)) continue;

    const definition = descriptor.manifest.definition;
    const agentHints =
      "agentHints" in definition && Array.isArray(definition.agentHints)
        ? definition.agentHints
        : [];

    for (const hint of agentHints) {
      const line = `${descriptor.manifest.definition.name}: ${hint}`;
      if (seen.has(line)) continue;
      seen.add(line);
      hints.push(line);
    }
  }

  return hints;
}
