// AUTO-GENERATED by plugins/installed/scripts/generate-surface-registries.mjs. Do not edit manually.
import {
  definePluginPackageDescriptors,
  extractPluginIds,
} from "@vivd/plugin-sdk";
import installedPluginManifest0 from "@vivd/plugin-google-maps/manifest";
import installedPluginManifest1 from "@vivd/plugin-contact-form/manifest";
import installedPluginManifest2 from "@vivd/plugin-analytics/manifest";
import installedPluginManifest3 from "@vivd/plugin-newsletter/manifest";
import installedPluginManifest4 from "@vivd/plugin-table-booking/manifest";

export const installedPluginManifests = definePluginPackageDescriptors([
  installedPluginManifest0,
  installedPluginManifest1,
  installedPluginManifest2,
  installedPluginManifest3,
  installedPluginManifest4,
  ] as const);

export const INSTALLED_PLUGIN_IDS = extractPluginIds(installedPluginManifests);
export type InstalledPluginId = (typeof INSTALLED_PLUGIN_IDS)[number];

export function listInstalledPluginAgentHints(
  enabledPluginIds?: readonly string[],
): string[] {
  const enabled = new Set(
    (enabledPluginIds ?? []).map((pluginId) => pluginId.trim()).filter(Boolean),
  );
  if (enabled.size === 0) return [];

  const seen = new Set<string>();
  const hints: string[] = [];

  for (const manifest of installedPluginManifests) {
    if (!enabled.has(manifest.pluginId)) continue;

    const definition = manifest.definition;
    const agentHints =
      "agentHints" in definition && Array.isArray(definition.agentHints)
        ? definition.agentHints
        : [];

    for (const hint of agentHints) {
      const line = `${manifest.definition.name}: ${hint}`;
      if (seen.has(line)) continue;
      seen.add(line);
      hints.push(line);
    }
  }

  return hints;
}
