import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { soloSelfHostDefaults } from "../packages/shared/src/config/selfHostDefaults.ts";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");

function composeVar(name: string, fallback?: string): string {
  if (fallback === undefined) return `\${${name}}`;
  return `\${${name}:-${fallback}}`;
}

function renderSoloSelfHostComposeBundle(): string {
  const defaults = soloSelfHostDefaults;
  const selfHostImageTag = composeVar("VIVD_SELFHOST_IMAGE_TAG", "latest");
  const networkName = defaults.dockerStudioNetwork;

  return [
    "services:",
    "  caddy:",
    `    image: ${defaults.caddyImage}`,
    "    restart: unless-stopped",
    '    ports:',
    '      - "80:80"',
    '      - "443:443"',
    "    environment:",
    `      - VIVD_CADDY_PRIMARY_HOST=${composeVar("VIVD_CADDY_PRIMARY_HOST")}`,
    `      - VIVD_CADDY_ACME_EMAIL=${composeVar("VIVD_CADDY_ACME_EMAIL", "")}`,
    "    volumes:",
    "      - ./Caddyfile:/etc/caddy/Caddyfile:ro",
    "      - caddy_data:/data",
    "      - caddy_config:/config",
    `      - caddy_sites:${defaults.caddySitesDir}`,
    `      - caddy_runtime_routes:${defaults.caddyRuntimeRoutesDir}:ro`,
    `      - published_sites:${defaults.publishedDir}:ro`,
    "    depends_on:",
    "      - backend",
    "      - minio",
    "    networks:",
    `      - ${networkName}`,
    "",
    "  backend:",
    `    image: ${defaults.serverImageRepository}:${selfHostImageTag}`,
    "    pull_policy: always",
    "    restart: unless-stopped",
    "    environment:",
    `      - DATABASE_URL=postgresql://${composeVar("POSTGRES_USER", defaults.postgresUser)}:${composeVar("POSTGRES_PASSWORD")}@postgres:5432/${composeVar("POSTGRES_DB", defaults.postgresDb)}`,
    `      - PORT=${defaults.backendPort}`,
    `      - BETTER_AUTH_SECRET=${composeVar("BETTER_AUTH_SECRET")}`,
    `      - OPENROUTER_API_KEY=${composeVar("OPENROUTER_API_KEY")}`,
    `      - GOOGLE_API_KEY=${composeVar("GOOGLE_API_KEY", "")}`,
    `      - GOOGLE_CLOUD_PROJECT=${composeVar("GOOGLE_CLOUD_PROJECT", "")}`,
    `      - VERTEX_LOCATION=${composeVar("VERTEX_LOCATION", "")}`,
    `      - GOOGLE_APPLICATION_CREDENTIALS=${composeVar("GOOGLE_APPLICATION_CREDENTIALS", "")}`,
    `      - GOOGLE_APPLICATION_CREDENTIALS_JSON=${composeVar("GOOGLE_APPLICATION_CREDENTIALS_JSON", "")}`,
    `      - VIVD_GOOGLE_APPLICATION_CREDENTIALS_PATH=${composeVar("VIVD_GOOGLE_APPLICATION_CREDENTIALS_PATH", "")}`,
    `      - OPENCODE_MODEL_STANDARD=${composeVar("OPENCODE_MODEL_STANDARD", "")}`,
    `      - OPENCODE_MODEL_ADVANCED=${composeVar("OPENCODE_MODEL_ADVANCED", "")}`,
    `      - OPENCODE_MODEL_PRO=${composeVar("OPENCODE_MODEL_PRO", "")}`,
    `      - DOMAIN=${composeVar("DOMAIN")}`,
    `      - BETTER_AUTH_URL=${composeVar("BETTER_AUTH_URL", "")}`,
    `      - VIVD_SCRATCH_CREATION_MODE=${composeVar("VIVD_SCRATCH_CREATION_MODE", defaults.scratchCreationMode)}`,
    `      - VIVD_CADDY_TLS_MODE=${composeVar("VIVD_CADDY_TLS_MODE", "off")}`,
    `      - VIVD_PUBLISH_INCLUDE_WWW_ALIAS=${composeVar("VIVD_PUBLISH_INCLUDE_WWW_ALIAS", "false")}`,
    `      - VIVD_PUBLIC_DOCS_BASE_URL=${composeVar("VIVD_PUBLIC_DOCS_BASE_URL", defaults.publicDocsBaseUrl)}`,
    `      - TRUSTED_DOMAINS=${composeVar("TRUSTED_DOMAINS", "")}`,
    `      - TENANT_BASE_DOMAIN=${composeVar("TENANT_BASE_DOMAIN", "")}`,
    `      - TENANT_DOMAIN_ROUTING_ENABLED=${composeVar("TENANT_DOMAIN_ROUTING_ENABLED", "false")}`,
    `      - CONTROL_PLANE_HOST=${composeVar("CONTROL_PLANE_HOST", "")}`,
    `      - SUPERADMIN_HOSTS=${composeVar("SUPERADMIN_HOSTS", "")}`,
    `      - BACKEND_URL=${composeVar("BACKEND_URL", "")}`,
    `      - VIVD_PUBLIC_PLUGIN_API_BASE_URL=${composeVar("VIVD_PUBLIC_PLUGIN_API_BASE_URL", "")}`,
    `      - PUBLISHED_DIR=${defaults.publishedDir}`,
    `      - CADDY_SITES_DIR=${defaults.caddySitesDir}`,
    `      - CADDY_RUNTIME_ROUTES_DIR=${defaults.caddyRuntimeRoutesDir}`,
    `      - CADDY_ADMIN_URL=${defaults.caddyAdminUrl}`,
    `      - SCRAPER_API_KEY=${composeVar("SCRAPER_API_KEY")}`,
    `      - CLOUDFLARE_ACCOUNT_ID=${composeVar("CLOUDFLARE_ACCOUNT_ID", "")}`,
    `      - CLOUDFLARE_API_TOKEN=${composeVar("CLOUDFLARE_API_TOKEN", "")}`,
    `      - VIVD_BUCKET_MODE=${composeVar("VIVD_BUCKET_MODE", defaults.bucketMode)}`,
    `      - VIVD_LOCAL_S3_BUCKET=${composeVar("VIVD_LOCAL_S3_BUCKET", "")}`,
    `      - VIVD_LOCAL_S3_ENDPOINT_URL=${composeVar("VIVD_LOCAL_S3_ENDPOINT_URL", "")}`,
    `      - VIVD_LOCAL_S3_DOWNLOAD_ENDPOINT_URL=${composeVar("VIVD_LOCAL_S3_DOWNLOAD_ENDPOINT_URL", "")}`,
    `      - VIVD_LOCAL_S3_ACCESS_KEY=${composeVar("VIVD_LOCAL_S3_ACCESS_KEY")}`,
    `      - VIVD_LOCAL_S3_SECRET_KEY=${composeVar("VIVD_LOCAL_S3_SECRET_KEY")}`,
    `      - VIVD_LOCAL_S3_REGION=${composeVar("VIVD_LOCAL_S3_REGION", "")}`,
    `      - R2_ENDPOINT=${composeVar("R2_ENDPOINT", "")}`,
    `      - R2_BUCKET=${composeVar("R2_BUCKET", "")}`,
    `      - R2_ACCESS_KEY=${composeVar("R2_ACCESS_KEY", "")}`,
    `      - R2_SECRET_KEY=${composeVar("R2_SECRET_KEY", "")}`,
    `      - VIVD_S3_BUCKET=${composeVar("VIVD_S3_BUCKET", "")}`,
    `      - VIVD_S3_ENDPOINT_URL=${composeVar("VIVD_S3_ENDPOINT_URL", "")}`,
    `      - VIVD_S3_ACCESS_KEY_ID=${composeVar("VIVD_S3_ACCESS_KEY_ID", "")}`,
    `      - VIVD_S3_SECRET_ACCESS_KEY=${composeVar("VIVD_S3_SECRET_ACCESS_KEY", "")}`,
    `      - VIVD_S3_SESSION_TOKEN=${composeVar("VIVD_S3_SESSION_TOKEN", "")}`,
    `      - VIVD_S3_REGION=${composeVar("VIVD_S3_REGION", "")}`,
    `      - VIVD_S3_DOWNLOAD_ENDPOINT_URL=${composeVar("VIVD_S3_DOWNLOAD_ENDPOINT_URL", "")}`,
    `      - VIVD_S3_PUBLIC_BASE_URL=${composeVar("VIVD_S3_PUBLIC_BASE_URL", "")}`,
    `      - VIVD_EMAIL_PROVIDER=${composeVar("VIVD_EMAIL_PROVIDER", "")}`,
    `      - EMAIL_PROVIDER=${composeVar("EMAIL_PROVIDER", "")}`,
    `      - RESEND_API_KEY=${composeVar("RESEND_API_KEY", "")}`,
    `      - RESEND_WEBHOOK_SECRET=${composeVar("RESEND_WEBHOOK_SECRET", "")}`,
    `      - VIVD_EMAIL_FROM=${composeVar("VIVD_EMAIL_FROM", "")}`,
    `      - VIVD_FROM_EMAIL=${composeVar("VIVD_FROM_EMAIL", "")}`,
    `      - VIVD_SMTP_URL=${composeVar("VIVD_SMTP_URL", "")}`,
    `      - VIVD_SMTP_HOST=${composeVar("VIVD_SMTP_HOST", "")}`,
    `      - VIVD_SMTP_PORT=${composeVar("VIVD_SMTP_PORT", "")}`,
    `      - VIVD_SMTP_SECURE=${composeVar("VIVD_SMTP_SECURE", "")}`,
    `      - VIVD_SMTP_USER=${composeVar("VIVD_SMTP_USER", "")}`,
    `      - VIVD_SMTP_PASSWORD=${composeVar("VIVD_SMTP_PASSWORD", "")}`,
    `      - VIVD_SMTP_REQUIRE_TLS=${composeVar("VIVD_SMTP_REQUIRE_TLS", "")}`,
    `      - VIVD_SMTP_IGNORE_TLS=${composeVar("VIVD_SMTP_IGNORE_TLS", "")}`,
    `      - VIVD_SMTP_FROM_EMAIL=${composeVar("VIVD_SMTP_FROM_EMAIL", "")}`,
    `      - VIVD_SES_ACCESS_KEY_ID=${composeVar("VIVD_SES_ACCESS_KEY_ID", "")}`,
    `      - VIVD_SES_SECRET_ACCESS_KEY=${composeVar("VIVD_SES_SECRET_ACCESS_KEY", "")}`,
    `      - VIVD_SES_FROM_EMAIL=${composeVar("VIVD_SES_FROM_EMAIL", "")}`,
    `      - VIVD_SES_REGION=${composeVar("VIVD_SES_REGION", "")}`,
    `      - STUDIO_MACHINE_PROVIDER=${composeVar("STUDIO_MACHINE_PROVIDER", defaults.studioMachineProvider)}`,
    `      - SINGLE_PROJECT_MODE=${composeVar("SINGLE_PROJECT_MODE", "false")}`,
    "      - VIVD_SELFHOST_UPDATE_WORKDIR=/srv/selfhost",
    "      - VIVD_SELFHOST_UPDATE_SERVICES=backend frontend scraper",
    `      - VIVD_SELFHOST_UPDATE_HELPER_IMAGE=${composeVar("VIVD_SELFHOST_UPDATE_HELPER_IMAGE", "docker:28-cli")}`,
    `      - DOCKER_STUDIO_SOCKET_PATH=${composeVar("DOCKER_STUDIO_SOCKET_PATH", defaults.dockerStudioSocketPath)}`,
    `      - DOCKER_STUDIO_API_BASE_URL=${composeVar("DOCKER_STUDIO_API_BASE_URL", "")}`,
    `      - DOCKER_STUDIO_API_VERSION=${composeVar("DOCKER_STUDIO_API_VERSION", "")}`,
    `      - DOCKER_STUDIO_NETWORK=${composeVar("DOCKER_STUDIO_NETWORK", defaults.dockerStudioNetwork)}`,
    `      - DOCKER_STUDIO_ROUTE_PREFIX=${composeVar("DOCKER_STUDIO_ROUTE_PREFIX", defaults.dockerStudioRoutePrefix)}`,
    `      - DOCKER_STUDIO_PUBLIC_BASE_URL=${composeVar("DOCKER_STUDIO_PUBLIC_BASE_URL", "")}`,
    `      - DOCKER_STUDIO_INTERNAL_PROXY_BASE_URL=${composeVar("DOCKER_STUDIO_INTERNAL_PROXY_BASE_URL", defaults.dockerStudioInternalProxyBaseUrl)}`,
    `      - DOCKER_STUDIO_IMAGE_REPO=${composeVar("DOCKER_STUDIO_IMAGE_REPO", "")}`,
    `      - DOCKER_STUDIO_IMAGE=${composeVar("DOCKER_STUDIO_IMAGE", "")}`,
    `      - DOCKER_STUDIO_CPUS=${composeVar("DOCKER_STUDIO_CPUS", "")}`,
    `      - DOCKER_STUDIO_CPUS_AUTO_RESERVE=${composeVar("DOCKER_STUDIO_CPUS_AUTO_RESERVE", "")}`,
    `      - DOCKER_STUDIO_CPUS_AUTO_MAX=${composeVar("DOCKER_STUDIO_CPUS_AUTO_MAX", "")}`,
    `      - DOCKER_STUDIO_MEMORY_MB=${composeVar("DOCKER_STUDIO_MEMORY_MB", "")}`,
    `      - DOCKER_STUDIO_MEMORY_AUTO_RESERVE_MB=${composeVar("DOCKER_STUDIO_MEMORY_AUTO_RESERVE_MB", "")}`,
    `      - DOCKER_STUDIO_MEMORY_AUTO_MIN_MB=${composeVar("DOCKER_STUDIO_MEMORY_AUTO_MIN_MB", "")}`,
    `      - DOCKER_STUDIO_MEMORY_AUTO_MAX_MB=${composeVar("DOCKER_STUDIO_MEMORY_AUTO_MAX_MB", "")}`,
    "    volumes:",
    "      - backend_data:/app/projects",
    "      - opencode_data:/root/.local/share/opencode/storage",
    `      - published_sites:${defaults.publishedDir}`,
    `      - caddy_sites:${defaults.caddySitesDir}`,
    `      - caddy_runtime_routes:${defaults.caddyRuntimeRoutesDir}`,
    "      - ./Caddyfile:/etc/caddy/Caddyfile",
    "      - ./:/srv/selfhost:ro",
    `      - ${defaults.dockerStudioSocketPath}:${defaults.dockerStudioSocketPath}`,
    "    depends_on:",
    "      postgres:",
    "        condition: service_healthy",
    "      scraper:",
    "        condition: service_healthy",
    "      minio:",
    "        condition: service_started",
    "    networks:",
    `      - ${networkName}`,
    "",
    "  frontend:",
    `    image: ${defaults.frontendImageRepository}:${selfHostImageTag}`,
    "    pull_policy: always",
    "    restart: unless-stopped",
    "    depends_on:",
    "      - backend",
    "    networks:",
    `      - ${networkName}`,
    "",
    "  scraper:",
    `    image: ${defaults.scraperImageRepository}:${selfHostImageTag}`,
    "    pull_policy: always",
    "    restart: unless-stopped",
    "    environment:",
    `      - PORT=${defaults.scraperPort}`,
    `      - MAX_BROWSERS=${composeVar("MAX_BROWSERS", "2")}`,
    `      - MAX_CONCURRENT_SCRAPES=${composeVar("MAX_CONCURRENT_SCRAPES", "2")}`,
    `      - SCRAPER_API_KEY=${composeVar("SCRAPER_API_KEY")}`,
    `      - OPENROUTER_API_KEY=${composeVar("OPENROUTER_API_KEY")}`,
    `      - PROXY_HOST=${composeVar("PROXY_HOST", "")}`,
    `      - PROXY_PORT=${composeVar("PROXY_PORT", "823")}`,
    `      - PROXY_USERNAME=${composeVar("PROXY_USERNAME", "")}`,
    `      - PROXY_PASSWORD=${composeVar("PROXY_PASSWORD", "")}`,
    "    healthcheck:",
    `      test: ["CMD", "node", "-e", "fetch('http://127.0.0.1:${defaults.scraperPort}/health').then((res) => { if (!res.ok) process.exit(1); }).catch(() => process.exit(1))"]`,
    "      interval: 15s",
    "      timeout: 10s",
    "      retries: 5",
    "      start_period: 30s",
    "    networks:",
    `      - ${networkName}`,
    "",
    "  postgres:",
    `    image: ${defaults.postgresImage}`,
    "    restart: unless-stopped",
    "    environment:",
    `      POSTGRES_USER: ${composeVar("POSTGRES_USER", defaults.postgresUser)}`,
    `      POSTGRES_PASSWORD: ${composeVar("POSTGRES_PASSWORD")}`,
    `      POSTGRES_DB: ${composeVar("POSTGRES_DB", defaults.postgresDb)}`,
    "    healthcheck:",
    `      test: ["CMD-SHELL", "pg_isready -U ${composeVar("POSTGRES_USER", defaults.postgresUser)} -d ${composeVar("POSTGRES_DB", defaults.postgresDb)}"]`,
    "      interval: 5s",
    "      timeout: 5s",
    "      retries: 5",
    "    volumes:",
    "      - postgres_data:/var/lib/postgresql/data",
    "    networks:",
    `      - ${networkName}`,
    "",
    "  minio:",
    `    image: ${composeVar("VIVD_LOCAL_S3_IMAGE", defaults.minioImage)}`,
    "    restart: unless-stopped",
    "    command: server /data --console-address :9001",
    "    environment:",
    `      MINIO_ROOT_USER: ${composeVar("VIVD_LOCAL_S3_ACCESS_KEY")}`,
    `      MINIO_ROOT_PASSWORD: ${composeVar("VIVD_LOCAL_S3_SECRET_KEY")}`,
    "    volumes:",
    "      - minio_data:/data",
    "    networks:",
    `      - ${networkName}`,
    "",
    "  minio-init:",
    `    image: ${composeVar("VIVD_LOCAL_S3_MC_IMAGE", defaults.minioMcImage)}`,
    '    restart: "no"',
    "    profiles:",
    "      - setup",
    "    depends_on:",
    "      - minio",
    "    environment:",
    `      - VIVD_LOCAL_S3_BUCKET=${composeVar("VIVD_LOCAL_S3_BUCKET", "")}`,
    `      - VIVD_LOCAL_S3_ENDPOINT_URL=${composeVar("VIVD_LOCAL_S3_ENDPOINT_URL", "")}`,
    `      - VIVD_LOCAL_S3_ACCESS_KEY=${composeVar("VIVD_LOCAL_S3_ACCESS_KEY")}`,
    `      - VIVD_LOCAL_S3_SECRET_KEY=${composeVar("VIVD_LOCAL_S3_SECRET_KEY")}`,
    "    entrypoint: >",
    "      /bin/sh -c '",
    '      until mc alias set vivd "$${VIVD_LOCAL_S3_ENDPOINT_URL:-' +
      defaults.localS3EndpointUrl +
      '}" "$$VIVD_LOCAL_S3_ACCESS_KEY" "$$VIVD_LOCAL_S3_SECRET_KEY" >/dev/null 2>&1; do',
    "        sleep 1",
    "      done &&",
    '      mc mb --ignore-existing "vivd/$${VIVD_LOCAL_S3_BUCKET:-' +
      defaults.localS3Bucket +
      '}"',
    "      '",
    "    networks:",
    `      - ${networkName}`,
    "",
    "volumes:",
    "  backend_data:",
    "  opencode_data:",
    "  published_sites:",
    "  caddy_data:",
    "  caddy_config:",
    "  caddy_sites:",
    "  caddy_runtime_routes:",
    "  postgres_data:",
    "  minio_data:",
    "",
    "networks:",
    `  ${networkName}:`,
    "    driver: bridge",
    "",
  ].join("\n");
}

function renderSoloSelfHostMinimalCompose(): string {
  const defaults = soloSelfHostDefaults;
  const selfHostImageTag = composeVar("VIVD_SELFHOST_IMAGE_TAG", "latest");
  const networkName = defaults.dockerStudioNetwork;

  return [
    "# Minimal solo self-host stack.",
    "# Put this next to the published Caddyfile asset and a matching .env file.",
    "# Fixed internal wiring stays in the compose file; the .env only covers values most installs change.",
    "",
    "services:",
    "  caddy:",
    `    image: ${defaults.caddyImage}`,
    "    restart: unless-stopped",
    "    ports:",
    '      - "80:80"',
    '      - "443:443"',
    "    environment:",
    `      VIVD_CADDY_PRIMARY_HOST: ${composeVar("VIVD_CADDY_PRIMARY_HOST")}`,
    `      VIVD_CADDY_ACME_EMAIL: ${composeVar("VIVD_CADDY_ACME_EMAIL", "")}`,
    "    volumes:",
    "      - ./Caddyfile:/etc/caddy/Caddyfile:ro",
    "      - caddy_data:/data",
    "      - caddy_config:/config",
    `      - caddy_sites:${defaults.caddySitesDir}`,
    `      - caddy_runtime_routes:${defaults.caddyRuntimeRoutesDir}:ro`,
    `      - published_sites:${defaults.publishedDir}:ro`,
    "    depends_on:",
    "      - backend",
    "      - minio",
    "    networks:",
    `      - ${networkName}`,
    "",
    "  backend:",
    `    image: ${defaults.serverImageRepository}:${selfHostImageTag}`,
    "    pull_policy: always",
    "    restart: unless-stopped",
    "    environment:",
    `      DATABASE_URL: postgresql://${defaults.postgresUser}:${composeVar("POSTGRES_PASSWORD")}@postgres:5432/${defaults.postgresDb}`,
    `      BETTER_AUTH_SECRET: ${composeVar("BETTER_AUTH_SECRET")}`,
    `      OPENROUTER_API_KEY: ${composeVar("OPENROUTER_API_KEY")}`,
    `      OPENCODE_MODEL_STANDARD: ${defaults.openCodeModelStandard}`,
    `      OPENCODE_MODEL_ADVANCED: ${defaults.openCodeModelAdvanced}`,
    `      DOMAIN: ${composeVar("DOMAIN")}`,
    `      VIVD_CADDY_TLS_MODE: ${composeVar("VIVD_CADDY_TLS_MODE", "managed")}`,
    `      STUDIO_MACHINE_PROVIDER: ${defaults.studioMachineProvider}`,
    "      VIVD_SELFHOST_UPDATE_WORKDIR: /srv/selfhost",
    "      VIVD_SELFHOST_UPDATE_SERVICES: backend frontend scraper",
    `      VIVD_SELFHOST_UPDATE_HELPER_IMAGE: ${composeVar("VIVD_SELFHOST_UPDATE_HELPER_IMAGE", "docker:28-cli")}`,
    `      VIVD_BUCKET_MODE: ${defaults.bucketMode}`,
    `      SCRAPER_API_KEY: ${composeVar("SCRAPER_API_KEY")}`,
    `      VIVD_LOCAL_S3_ACCESS_KEY: ${composeVar("VIVD_LOCAL_S3_ACCESS_KEY")}`,
    `      VIVD_LOCAL_S3_SECRET_KEY: ${composeVar("VIVD_LOCAL_S3_SECRET_KEY")}`,
    `      DOCKER_STUDIO_IMAGE: ${defaults.dockerStudioImageRepository}:${selfHostImageTag}`,
    "    volumes:",
    "      - backend_data:/app/projects",
    "      - opencode_data:/root/.local/share/opencode/storage",
    `      - published_sites:${defaults.publishedDir}`,
    `      - caddy_sites:${defaults.caddySitesDir}`,
    `      - caddy_runtime_routes:${defaults.caddyRuntimeRoutesDir}`,
    "      - ./Caddyfile:/etc/caddy/Caddyfile",
    "      - ./:/srv/selfhost:ro",
    `      - ${defaults.dockerStudioSocketPath}:${defaults.dockerStudioSocketPath}`,
    "    depends_on:",
    "      postgres:",
    "        condition: service_healthy",
    "      scraper:",
    "        condition: service_healthy",
    "      minio:",
    "        condition: service_started",
    "    networks:",
    `      - ${networkName}`,
    "",
    "  frontend:",
    `    image: ${defaults.frontendImageRepository}:${selfHostImageTag}`,
    "    pull_policy: always",
    "    restart: unless-stopped",
    "    depends_on:",
    "      - backend",
    "    networks:",
    `      - ${networkName}`,
    "",
    "  scraper:",
    `    image: ${defaults.scraperImageRepository}:${selfHostImageTag}`,
    "    pull_policy: always",
    "    restart: unless-stopped",
    "    environment:",
    `      SCRAPER_API_KEY: ${composeVar("SCRAPER_API_KEY")}`,
    `      OPENROUTER_API_KEY: ${composeVar("OPENROUTER_API_KEY")}`,
    "    healthcheck:",
    `      test: ["CMD", "node", "-e", "fetch('http://127.0.0.1:${defaults.scraperPort}/health').then((res) => { if (!res.ok) process.exit(1); }).catch(() => process.exit(1))"]`,
    "      interval: 15s",
    "      timeout: 10s",
    "      retries: 5",
    "      start_period: 30s",
    "    networks:",
    `      - ${networkName}`,
    "",
    "  postgres:",
    `    image: ${defaults.postgresImage}`,
    "    restart: unless-stopped",
    "    environment:",
    `      POSTGRES_USER: ${defaults.postgresUser}`,
    `      POSTGRES_PASSWORD: ${composeVar("POSTGRES_PASSWORD")}`,
    `      POSTGRES_DB: ${defaults.postgresDb}`,
    "    healthcheck:",
    `      test: ["CMD-SHELL", "pg_isready -U ${defaults.postgresUser} -d ${defaults.postgresDb}"]`,
    "      interval: 5s",
    "      timeout: 5s",
    "      retries: 5",
    "    volumes:",
    "      - postgres_data:/var/lib/postgresql/data",
    "    networks:",
    `      - ${networkName}`,
    "",
    "  minio:",
    `    image: ${defaults.minioImage}`,
    "    restart: unless-stopped",
    "    command: server /data --console-address :9001",
    "    environment:",
    `      MINIO_ROOT_USER: ${composeVar("VIVD_LOCAL_S3_ACCESS_KEY")}`,
    `      MINIO_ROOT_PASSWORD: ${composeVar("VIVD_LOCAL_S3_SECRET_KEY")}`,
    "    volumes:",
    "      - minio_data:/data",
    "    networks:",
    `      - ${networkName}`,
    "",
    "  minio-init:",
    `    image: ${defaults.minioMcImage}`,
    '    restart: "no"',
    "    profiles:",
    "      - setup",
    "    depends_on:",
    "      - minio",
    "    environment:",
    `      VIVD_LOCAL_S3_ACCESS_KEY: ${composeVar("VIVD_LOCAL_S3_ACCESS_KEY")}`,
    `      VIVD_LOCAL_S3_SECRET_KEY: ${composeVar("VIVD_LOCAL_S3_SECRET_KEY")}`,
    "    entrypoint: >",
    "      /bin/sh -c '",
    `      until mc alias set vivd ${defaults.localS3EndpointUrl} "$$VIVD_LOCAL_S3_ACCESS_KEY" "$$VIVD_LOCAL_S3_SECRET_KEY" >/dev/null 2>&1; do`,
    "        sleep 1",
    "      done &&",
    `      mc mb --ignore-existing "vivd/${defaults.localS3Bucket}"`,
    "      '",
    "    networks:",
    `      - ${networkName}`,
    "",
    "volumes:",
    "  backend_data:",
    "  opencode_data:",
    "  published_sites:",
    "  caddy_data:",
    "  caddy_config:",
    "  caddy_sites:",
    "  caddy_runtime_routes:",
    "  postgres_data:",
    "  minio_data:",
    "",
    "networks:",
    `  ${networkName}:`,
    "    driver: bridge",
    "",
  ].join("\n");
}

function renderStudioSelfHostDefaultsShell(): string {
  return [
    "#!/bin/sh",
    "# Generated by `npm run sync:self-host-assets`. Do not edit by hand.",
    `VIVD_SELFHOST_DEFAULT_LOCAL_S3_BUCKET="${soloSelfHostDefaults.localS3Bucket}"`,
    `VIVD_SELFHOST_DEFAULT_LOCAL_S3_ENDPOINT_URL="${soloSelfHostDefaults.localS3EndpointUrl}"`,
    `VIVD_SELFHOST_DEFAULT_LOCAL_S3_REGION="${soloSelfHostDefaults.localS3Region}"`,
    "",
  ].join("\n");
}

function renderInstallScriptDefaultsBlock(): string {
  return [
    "# BEGIN GENERATED SELF-HOST DEFAULTS",
    `DEFAULT_POSTGRES_USER="${soloSelfHostDefaults.postgresUser}"`,
    `DEFAULT_POSTGRES_DB="${soloSelfHostDefaults.postgresDb}"`,
    `DEFAULT_STUDIO_MACHINE_PROVIDER="${soloSelfHostDefaults.studioMachineProvider}"`,
    `DEFAULT_VIVD_BUCKET_MODE="${soloSelfHostDefaults.bucketMode}"`,
    `DEFAULT_OPENCODE_MODEL_STANDARD="${soloSelfHostDefaults.openCodeModelStandard}"`,
    `DEFAULT_OPENCODE_MODEL_ADVANCED="${soloSelfHostDefaults.openCodeModelAdvanced}"`,
    `DEFAULT_DOCKER_STUDIO_IMAGE_REPOSITORY="${soloSelfHostDefaults.dockerStudioImageRepository}"`,
    "# END GENERATED SELF-HOST DEFAULTS",
  ].join("\n");
}

async function writeIfChanged(filePath: string, nextContent: string): Promise<void> {
  const normalized = nextContent.endsWith("\n") ? nextContent : `${nextContent}\n`;
  const current = await fs.readFile(filePath, "utf8").catch(() => null);
  if (current === normalized) return;
  await fs.writeFile(filePath, normalized, "utf8");
}

async function syncInstallScript(): Promise<void> {
  const installScriptPath = path.join(repoRoot, "packages/docs/public/install.sh");
  const current = await fs.readFile(installScriptPath, "utf8");
  const next = current.replace(
    /# BEGIN GENERATED SELF-HOST DEFAULTS[\s\S]*?# END GENERATED SELF-HOST DEFAULTS/m,
    renderInstallScriptDefaultsBlock(),
  );
  if (next === current) return;
  await fs.writeFile(installScriptPath, next, "utf8");
}

async function main(): Promise<void> {
  await Promise.all([
    writeIfChanged(
      path.join(repoRoot, "packages/docs/public/install/docker-compose.yml"),
      renderSoloSelfHostComposeBundle(),
    ),
    writeIfChanged(
      path.join(repoRoot, "packages/docs/src/snippets/self-hosting/docker-compose.minimal.yml"),
      renderSoloSelfHostMinimalCompose(),
    ),
    writeIfChanged(
      path.join(repoRoot, "packages/studio/selfHostDefaults.sh"),
      renderStudioSelfHostDefaultsShell(),
    ),
  ]);

  await syncInstallScript();
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
