#!/bin/sh
# Generated by `npm run sync:self-host-assets`. Do not edit by hand.
VIVD_SELFHOST_DEFAULT_LOCAL_S3_BUCKET="vivd"
VIVD_SELFHOST_DEFAULT_LOCAL_S3_ENDPOINT_URL="http://minio:9000"
VIVD_SELFHOST_DEFAULT_LOCAL_S3_REGION="us-east-1"
